context:
  name: lazyjournal
  version: "0.8.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/Lifailon/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 5fb748c05ea9feb2fb957dfcac79db8b80a27afc1733b0ca3fc58046ad3e96eb

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - ${{ stdlib('c') }}
    - go-licenses

tests:
  - script: lazyjournal --version

about:
  homepage: https://github.com/Lifailon/lazyjournal
  summary: 'TUI for logs from journalctl, file system, Docker, Podman and Kubernetes pods'
  description: |
    Terminal user interface for reading logs from journalctl, file system, Docker and Podman containers,
    as well Kubernetes pods for quick viewing and filtering with fuzzy find (like fzf), regex support (like grep) and coloring the output,
    written in Go with the awesome-gocui (fork gocui) library.

    This tool is inspired by and with love for LazyDocker and LazyGit,
    as well as is included in Awesome-TUIs and Awesome-Docker, check out other useful projects on the repository pages.
  license: MIT
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - eunos-1128
